In [1]:
import numpy as np
from sklearn import datasets

In [61]:
digits=datasets.load_digits()
x=digits.data
y=digits.target

In [62]:
len(x)

1797

In [3]:
x_c=digits.data[:-150]
x_m=digits.data[-150:]
y_c=digits.target[:-150]
y_m=digits.target[-150:]

In [4]:
len(x_c)

1647

In [5]:
len(x_m)

150

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_c,y_c)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [7]:
y_pw=knn.predict(x_m)

In [8]:
y_pw

array([6, 1, 7, 5, 4, 4, 7, 2, 2, 5, 7, 3, 5, 4, 4, 5, 0, 8, 9, 8, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 2, 7, 3, 3, 4, 6, 6, 6,
       4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4, 6, 3,
       1, 3, 9, 1, 7, 6, 8, 4, 5, 1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 1, 4, 9, 0, 8, 9, 8])

In [9]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_m,y_pw)
print(cnf_matrix)

[[14  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0]
 [ 0  0  1 11  0  1  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0]
 [ 0  0  0  0  0 16  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0]
 [ 0  1  0  0  0  0  0  0 14  0]
 [ 0  0  0  1  0  1  0  0  0 14]]


In [10]:
acc_sc=accuracy_score(y_m, y_pw)
print(acc_sc)

0.9666666666666667


In [11]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_c=list(x_folds)
    x_m=x_c.pop(k)           
    x_c=np.concatenate(x_c)
    y_c=list(y_folds)
    y_m=y_c.pop(k)
    y_c=np.concatenate(y_c)
    scores.append(knn.fit(x_c,y_c).score(x_m,y_m))
print(scores)

[0.9277777777777778, 0.9888888888888889, 0.9888888888888889, 0.9777777777777777, 0.9611111111111111, 0.9777777777777777, 0.9888888888888889, 0.9832402234636871, 0.9832402234636871, 0.9608938547486033]


In [12]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier()

In [13]:
x_tx=digits.data[:-150]
y_tx=digits.target[:-150]
x_ty=digits.data[-150:]
y_ty=digits.target[-150:]

In [14]:
decision_tree.fit(x_tx,y_tx)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [15]:
y_predf=decision_tree.predict(x_ty)
y_predf

array([4, 1, 7, 5, 4, 4, 7, 8, 2, 5, 7, 8, 5, 4, 4, 9, 0, 5, 7, 7, 0, 8,
       2, 5, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 8, 2, 1,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 6, 2, 7, 8, 2, 0, 1, 2, 6, 2, 2, 7, 4, 3, 4, 6, 6, 6,
       4, 9, 1, 6, 0, 9, 5, 3, 8, 8, 0, 0, 4, 7, 6, 3, 2, 1, 7, 4, 6, 3,
       1, 3, 9, 1, 7, 6, 8, 4, 5, 1, 6, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 4, 7, 9, 3, 4, 8, 8, 4, 9, 0, 8, 9, 8])

In [16]:
y_ty

array([6, 1, 7, 5, 4, 4, 7, 2, 2, 5, 7, 9, 5, 4, 4, 9, 0, 8, 9, 8, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7, 3, 3, 4, 6, 6, 6,
       4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4, 6, 3,
       1, 3, 9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9, 0, 8, 9, 8])

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_ty ,y_predf)
print(cnf_matrix)

[[14  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  1  0  0  0  2  0]
 [ 0  0 11  1  0  0  1  0  2  0]
 [ 0  1  2  7  1  2  0  0  0  0]
 [ 0  0  0  0 16  0  1  0  0  0]
 [ 0  0  0  1  1 13  1  0  0  0]
 [ 0  0  0  0  1  0 13  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0]
 [ 0  0  0  0  0  1  0  1 13  0]
 [ 0  0  0  0  0  0  0  1  1 14]]


In [19]:
acc_sc=accuracy_score(y_ty, y_predf)
print(acc_sc)

0.8533333333333334


In [20]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_tx=list(x_folds)
    x_ty=x_tx.pop(k)           
    x_tx=np.concatenate(x_tx)
    y_tx=list(y_folds)
    y_ty=y_tx.pop(k)
    y_tx=np.concatenate(y_tx)
    scores.append(decision_tree.fit(x_tx,y_tx).score(x_ty,y_ty))
print(scores)

[0.8111111111111111, 0.8666666666666667, 0.8222222222222222, 0.8444444444444444, 0.7722222222222223, 0.9, 0.8666666666666667, 0.8435754189944135, 0.8491620111731844, 0.8156424581005587]


In [27]:
from sklearn.naive_bayes import GaussianNB
naive_bayes=GaussianNB()

In [28]:
x_j=digits.data[:-150]
x_a=digits.data[-150:]
y_j=digits.target[:-150]
y_a=digits.target[-150:]

In [29]:
naive_bayes.fit(x_j,y_j)

GaussianNB(priors=None, var_smoothing=1e-09)

In [30]:
y_ph=naive_bayes.predict(x_a)

In [31]:
y_ph

array([6, 1, 7, 7, 4, 7, 7, 6, 2, 5, 5, 1, 5, 7, 4, 5, 0, 7, 7, 7, 0, 8,
       2, 5, 4, 5, 6, 7, 8, 9, 0, 1, 8, 8, 4, 5, 6, 7, 8, 9, 0, 1, 2, 5,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 7, 1, 7, 7, 7,
       5, 1, 0, 0, 8, 2, 7, 8, 2, 0, 1, 2, 6, 8, 8, 8, 5, 8, 4, 6, 6, 6,
       4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 8, 7, 6, 3, 8, 1, 7, 4, 6, 3,
       8, 3, 9, 1, 7, 6, 8, 4, 5, 1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 1, 4, 9, 0, 8, 9, 8])

In [32]:
y_a

array([6, 1, 7, 5, 4, 4, 7, 2, 2, 5, 7, 9, 5, 4, 4, 9, 0, 8, 9, 8, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7, 3, 3, 4, 6, 6, 6,
       4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4, 6, 3,
       1, 3, 9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9, 0, 8, 9, 8])

In [33]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_a ,y_ph)
print(cnf_matrix)

[[14  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  3  0]
 [ 0  0 11  0  0  0  1  0  3  0]
 [ 0  0  0  4  0  4  0  1  4  0]
 [ 0  0  0  0 14  0  0  3  0  0]
 [ 0  0  0  0  0 15  0  1  0  0]
 [ 0  0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  1  0 14  1  0]
 [ 0  1  0  0  0  0  0  2 12  0]
 [ 0  1  0  0  0  1  0  1  0 13]]


In [34]:
acc_sc=accuracy_score(y_a, y_ph)
print(acc_sc)

0.8133333333333334


In [35]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_j=list(x_folds)
    x_a=x_j.pop(k)           
    x_j=np.concatenate(x_j)
    y_j=list(y_folds)
    y_a=y_j.pop(k)
    y_j=np.concatenate(y_j)
    scores.append(naive_bayes.fit(x_j,y_j).score(x_a,y_a))
print(scores)

[0.7722222222222223, 0.8166666666666667, 0.8833333333333333, 0.7166666666666667, 0.7166666666666667, 0.8611111111111112, 0.8444444444444444, 0.88268156424581, 0.8212290502793296, 0.8156424581005587]


In [51]:
from sklearn import datasets,svm

In [52]:
digits=datasets.load_digits()
x=digits.data
y=digits.target

In [53]:
x_g=digits.data[:-150]
x_s=digits.data[-150:]
y_g=digits.target[:-150]
y_s=digits.target[-150:]

In [54]:
svc=svm.SVC(C=1,kernel='linear')
svc.fit(x_g[:-100],y_g[:-100]) 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [55]:
y_pt=svc.predict(x_s)
y_pt

array([6, 1, 7, 5, 4, 4, 7, 2, 2, 5, 7, 8, 5, 9, 4, 1, 0, 8, 9, 8, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 8,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 8, 7, 5, 8, 4, 6, 6, 6,
       4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4, 6, 3,
       1, 3, 9, 1, 7, 6, 8, 4, 5, 1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9, 0, 8, 9, 8])

In [56]:
y_s

array([6, 1, 7, 5, 4, 4, 7, 2, 2, 5, 7, 9, 5, 4, 4, 9, 0, 8, 9, 8, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3,
       5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7, 3, 3, 4, 6, 6, 6,
       4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4, 6, 3,
       1, 3, 9, 1, 7, 6, 8, 4, 3, 1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4,
       7, 2, 8, 2, 2, 5, 7, 9, 5, 4, 8, 8, 4, 9, 0, 8, 9, 8])

In [57]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_s ,y_pt)
print(cnf_matrix)

[[14  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  2  0  0  3  0]
 [ 0  0  0  0 16  0  0  0  0  1]
 [ 0  0  0  0  0 16  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0]
 [ 0  0  0  0  0  0  0  0 15  0]
 [ 0  1  0  0  0  0  0  0  1 14]]


In [58]:
acc_sc=accuracy_score(y_s, y_pt)
print(acc_sc)

0.9466666666666667


In [60]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_g=list(x_folds)
    x_s=x_g.pop(k)           
    x_g=np.concatenate(x_g)
    y_g=list(y_folds)
    y_s=y_g.pop(k)
    y_g=np.concatenate(y_g)
    scores.append(svc.fit(x_g,y_g).score(x_s,y_s))
print(scores)

[0.9388888888888889, 0.9944444444444445, 0.9333333333333333, 0.9666666666666667, 0.9611111111111111, 0.9888888888888889, 0.9666666666666667, 0.9888268156424581, 0.9329608938547486, 0.9664804469273743]


In [1]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
x=iris.data
y=iris.target
np.random.seed(0)
indices=np.random.permutation(len(x))
x_xbn=x[indices[:-30]]
y_xbn=y[indices[:-30]]
x_xbc=x[indices[-30:]]
y_xbc=y[indices[-30:]]
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(x_xbn,y_xbn)
y_pr_mlp=mlp.predict(x_xbc)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_xbc,y_pr_mlp)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_xbc, y_pr_mlp)
print(acc_sc) 

[[10  0  0]
 [ 0  9  2]
 [ 0  0  9]]
0.9333333333333333


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [2]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
x=iris.data
y=iris.target
np.random.seed(40)
indices=np.random.permutation(len(x))
x_xbn=x[indices[:-30]]
y_xbn=y[indices[:-30]]
x_xbc=x[indices[-30:]]
y_xbc=y[indices[-30:]]
from sklearn.linear_model import Perceptron
sp=Perceptron()
sp.fit(x_xbn,y_xbn)
y_pr_sp=sp.predict(x_xbc)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_xbc,y_pr_sp)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_xbc,y_pr_sp)
print(acc_sc)

[[12  0  0]
 [ 0 10  1]
 [ 0  0  7]]
0.9666666666666667


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
