# REGRESSION

# 1. Boston Dataset

In [26]:
import numpy as np

In [27]:
from sklearn import datasets

In [28]:
boston=datasets.load_boston()
x=boston.data
y=boston.target

In [29]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [30]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [31]:
x_train=boston.data[:-20]
y_train=boston.target[:-20]
x_test=boston.data[-20:]
y_test=boston.target[-20:]

In [32]:
from sklearn import linear_model
regr=linear_model.LinearRegression()
regr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [33]:
y_pred=regr.predict(x_test)

In [34]:
regr.predict(x_train)

array([29.97144116, 25.22448071, 30.76834191, 28.90465284, 28.22048704,
       25.5935577 , 22.9298559 , 19.46086675, 11.20528929, 18.86093348,
       18.8786789 , 21.60335368, 20.5808839 , 19.78791978, 19.59796849,
       19.49562527, 20.61239048, 17.08709224, 16.20649553, 18.60050285,
       12.64045561, 17.91046747, 15.94650863, 13.95375499, 15.88761597,
       13.58469265, 15.70598031, 14.88593476, 19.83467536, 21.13555959,
       11.51118146, 18.39302177,  8.68467041, 14.45363619, 13.85887792,
       24.02912235, 22.47836705, 23.19897221, 22.89428039, 31.5583658 ,
       34.42603976, 27.93583833, 25.14010012, 24.4953951 , 22.98129559,
       22.08251419, 20.29404047, 18.10161655,  8.93009309, 17.22162398,
       21.28045097, 24.18109127, 27.70542555, 24.03478315, 14.89012372,
       31.54828987, 24.88806151, 33.45265478, 22.07559037, 21.4208829 ,
       18.2307062 , 18.98969915, 24.50152384, 22.84522327, 23.6945556 ,
       30.19854352, 25.31667766, 20.81427144, 17.09152245, 20.53

In [36]:
y_xk=regr.predict(x_test)
y_xk

array([19.52851487, 21.13030683, 10.69052057,  6.94917077,  2.25423441,
       12.61186689, 14.82173569, 20.44306906, 20.30781014, 16.40520255,
       13.71615353, 18.97549154, 21.14696273, 18.3123007 , 20.36823484,
       23.73106449, 22.649771  , 28.04655708, 26.5264822 , 22.68372601])

In [37]:
print(regr.coef_)

[-1.02735683e-01  4.95114312e-02  2.30184437e-02  2.59133809e+00
 -1.67932866e+01  3.76972692e+00  6.80267183e-03 -1.45744398e+00
  3.50562658e-01 -1.56989298e-02 -9.03076189e-01  8.96753250e-03
 -5.52127828e-01]


# 2. Linnerud Dataset

In [16]:
from sklearn import datasets
linnerud=datasets.load_linnerud()
x=linnerud.data
y=linnerud.target

In [17]:
x

array([[  5., 162.,  60.],
       [  2., 110.,  60.],
       [ 12., 101., 101.],
       [ 12., 105.,  37.],
       [ 13., 155.,  58.],
       [  4., 101.,  42.],
       [  8., 101.,  38.],
       [  6., 125.,  40.],
       [ 15., 200.,  40.],
       [ 17., 251., 250.],
       [ 17., 120.,  38.],
       [ 13., 210., 115.],
       [ 14., 215., 105.],
       [  1.,  50.,  50.],
       [  6.,  70.,  31.],
       [ 12., 210., 120.],
       [  4.,  60.,  25.],
       [ 11., 230.,  80.],
       [ 15., 225.,  73.],
       [  2., 110.,  43.]])

In [18]:
y

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.],
       [182.,  36.,  56.],
       [211.,  38.,  56.],
       [167.,  34.,  60.],
       [176.,  31.,  74.],
       [154.,  33.,  56.],
       [169.,  34.,  50.],
       [166.,  33.,  52.],
       [154.,  34.,  64.],
       [247.,  46.,  50.],
       [193.,  36.,  46.],
       [202.,  37.,  62.],
       [176.,  37.,  54.],
       [157.,  32.,  52.],
       [156.,  33.,  54.],
       [138.,  33.,  68.]])

In [19]:
x_tr=linnerud.data[:-10]
y_tr=linnerud.target[:-10]
x_te=linnerud.data[-10:]
y_te=linnerud.target[-10:]

In [21]:
from sklearn import linear_model
regr=linear_model.LinearRegression()
regr.fit(x_tr,y_tr)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [23]:
y_xa=regr.predict(x_te)
y_xa

array([[181.76627517,  34.8385222 ,  64.57535996],
       [170.8517086 ,  32.75241713,  59.25385156],
       [170.35793624,  32.22731251,  60.85036003],
       [195.42664147,  39.69788304,  48.97410287],
       [192.04698816,  37.94532214,  54.78232726],
       [171.06558569,  32.9476538 ,  58.14037842],
       [194.22521967,  38.45243712,  53.28059293],
       [171.30477279,  31.30121265,  60.58527984],
       [170.36279457,  31.01723985,  64.03574244],
       [189.19787361,  36.75574891,  52.11113869]])

In [24]:
print(regr.coef_)

[[-0.44285531 -0.1017747  -0.04579565]
 [-0.09079547 -0.04508535  0.02088824]
 [ 0.78822649  0.03155773 -0.06504933]]


# 3. Diabetes Dataset

In [52]:
diabetes=datasets.load_diabetes()

In [53]:
x_tn=diabetes.data[:-20]

In [54]:
y_tn=diabetes.target[:-20]

In [55]:
x_tst=diabetes.data[-20:]

In [56]:
y_tst=diabetes.target[-20:]

In [78]:
from sklearn import linear_model
regr=linear_model.LinearRegression()
regr.fit(x_tn,y_tn)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [81]:
y_pred=regr.predict(x_tst)

In [82]:
regr.predict(x_tn)

array([206.75928628,  68.44064739, 178.20406005, 166.59039906,
       129.47338697, 105.48206978,  74.90024045, 120.73067569,
       159.82011958, 211.92833532,  97.83664191,  97.41005509,
       115.60592349, 164.92279039, 103.34070745, 177.68217359,
       210.75217394, 184.40013153, 148.54098532, 123.55941211,
       120.97403176,  86.41241445, 113.06547293, 252.35802827,
       165.0256223 , 147.87909701,  97.36674337, 179.12350572,
       129.58494812, 185.38814558, 158.11930901,  69.5502975 ,
       263.36897831, 113.46175282,  79.56563326,  87.72481273,
       207.0421844 , 157.45915639, 240.65662115, 137.1490856 ,
       155.31655344,  74.42879297, 146.31653437,  78.52705268,
       222.11926084, 126.59820508, 141.84166437, 109.44753606,
        75.09372891, 190.42332738, 159.23790309, 171.06440722,
       134.14185441, 159.31230491, 138.94279895,  73.39607055,
       207.21538369,  80.45498482, 103.89405947, 135.51866843,
       113.7604739 , 181.57058967,  61.77249359,  98.88

In [61]:
print(regr.coef_)

[ 3.03499549e-01 -2.37639315e+02  5.10530605e+02  3.27736980e+02
 -8.14131709e+02  4.92814588e+02  1.02848452e+02  1.84606489e+02
  7.43519617e+02  7.60951722e+01]


# 4. California Housing Dataset

In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
c_h=fetch_california_housing()

In [3]:
x=c_h.data
y=c_h.target

In [4]:
x_xc=c_h.data[:-4000]
y_xc=c_h.target[:-4000]
x_yc=c_h.data[-4000:]
y_yc=c_h.target[-4000:]

In [5]:
from sklearn import linear_model
regr=linear_model.LinearRegression()

In [6]:
regr.fit(x_xc,y_xc)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
y_xk=regr.predict(x_yc)
y_xk

array([1.88791547, 1.73435785, 1.55363173, ..., 0.14172157, 0.29296784,
       0.4952042 ])

In [8]:
print(regr.coef_)

[ 4.47711234e-01  9.40915756e-03 -1.20802393e-01  7.09551707e-01
 -1.82577993e-06 -8.83342492e-03 -4.21683195e-01 -4.29077083e-01]
