In [1]:
import numpy as np

In [2]:
from sklearn import datasets  

In [3]:
iris=datasets.load_iris()
x=iris.data
y=iris.target

In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
len(x)

150

In [7]:
len(y)

150

In [8]:
indices=np.random.permutation(len(x))

In [19]:
iris_x_train=x[indices[:-30]]
iris_y_train=y[indices[:-30]]
iris_x_test=x[indices[-30:]]
iris_y_test=y[indices[-30:]]

In [18]:
len(iris_x_train)

120

In [20]:
len(iris_y_train)

120

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(iris_x_train,iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [25]:
t=knn.predict(iris_x_test)
t

array([1, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 0, 2, 2,
       1, 2, 2, 0, 2, 2, 1, 2])

In [23]:
iris_y_test

array([1, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 0, 2, 2,
       1, 2, 2, 0, 2, 1, 1, 2])

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(iris_y_test,t)
print(cnf_matrix)

[[ 7  0  0]
 [ 0  8  1]
 [ 0  0 14]]


In [27]:
acc_sc=accuracy_score(iris_y_test, t)
print(acc_sc)

0.9666666666666667


In [30]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    iris_x_train=list(x_folds)
    iris_x_test=iris_x_train.pop(k)           
    iris_x_train=np.concatenate(iris_x_train)
    iris_y_train=list(y_folds)
    iris_y_test=iris_y_train.pop(k)
    iris_y_train=np.concatenate( iris_y_train)
    scores.append(knn.fit(iris_x_train,iris_y_train).score(iris_x_test,iris_y_test))
print(scores)

[1.0, 1.0, 1.0, 1.0, 0.8, 0.8666666666666667, 1.0, 0.8666666666666667, 0.8, 1.0]


In [38]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier()

In [51]:
x_tj=iris.data[:-30]
y_tj=iris.target[:-30]
x_tk=iris.data[-30:]
y_tk=iris.target[-30:]

In [52]:
decision_tree.fit(x_tj,y_tj)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [53]:
y_predh=decision_tree.predict(x_tk)
y_predh

array([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [54]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_tk ,y_predh)
print(cnf_matrix)

[[ 0  0]
 [ 8 22]]


In [55]:
acc_sc=accuracy_score(y_tk, y_predh)
print(acc_sc)

0.7333333333333333


In [56]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_tj=list(x_folds)
    x_tk=x_tj.pop(k)           
    x_tj=np.concatenate(x_tj)
    y_tj=list(y_folds)
    y_tk=y_tj.pop(k)
    y_tj=np.concatenate(y_tj)
    scores.append(decision_tree.fit(x_tj,y_tj).score(x_tk,y_tk))
print(scores)

[1.0, 1.0, 1.0, 0.9333333333333333, 0.9333333333333333, 0.8666666666666667, 1.0, 0.8666666666666667, 0.7333333333333333, 1.0]


In [57]:
from sklearn.naive_bayes import GaussianNB
naive_bayes=GaussianNB()

In [58]:
x_j=iris.data[:-30]
x_a=iris.data[-30:]
y_j=iris.target[:-30]
y_a=iris.target[-30:]

In [59]:
naive_bayes.fit(x_j,y_j)

GaussianNB(priors=None, var_smoothing=1e-09)

In [61]:
y_ph=naive_bayes.predict(x_a)
y_ph

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [62]:
y_a

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [63]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_a ,y_ph)
print(cnf_matrix)

[[ 0  0]
 [ 2 28]]


In [64]:
acc_sc=accuracy_score(y_a, y_ph)
print(acc_sc)

0.9333333333333333


In [65]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_j=list(x_folds)
    x_a=x_j.pop(k)           
    x_j=np.concatenate(x_j)
    y_j=list(y_folds)
    y_a=y_j.pop(k)
    y_j=np.concatenate(y_j)
    scores.append(naive_bayes.fit(x_j,y_j).score(x_a,y_a))
print(scores)

[1.0, 1.0, 1.0, 0.9333333333333333, 0.9333333333333333, 0.8666666666666667, 1.0, 0.8666666666666667, 0.8666666666666667, 1.0]


In [24]:
from sklearn import datasets,svm
import numpy as np

In [25]:
digits=datasets.load_digits()
x=iris.data
y=iris.target

In [26]:
x_gh=iris.data[:-30]
y_gh=iris.target[:-30]
x_hg=iris.data[-30:]
y_hg=iris.target[-30:]

In [27]:
svc=svm.SVC(C=1,kernel='linear')
svc.fit(x_gh[:-30],y_gh[:-30]) 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [28]:
y_pt=svc.predict(x_hg)
y_pt

array([4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5, 4,
       8, 8, 4, 9, 0, 8, 9, 8])

In [29]:
y_hg

array([4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5, 4,
       8, 8, 4, 9, 0, 8, 9, 8])

In [30]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_hg ,y_pt)
print(cnf_matrix)

[[2 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 0 4]]


In [31]:
acc_sc=accuracy_score(y_hg, y_pt)
print(acc_sc)

1.0


In [32]:
y_kl=svc.predict(x_hg)

In [34]:
np.random.seed(0)
indices=np.random.permutation(len(x))
x_gh=x[indices[:-10]]
y_gh=y[indices[:-10]]
x_hg=x[indices[-10:]]
y_hg=y[indices[-10:]]
svc.fit(x_gh,y_gh)
y_hg
y_kl
y_kl=svc.predict(x_hg)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_hg,y_kl)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_hg, y_kl)
print(acc_sc)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]]
1.0


In [37]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_gh=list(x_folds)
    x_hg=x_gh.pop(k)           
    x_gh=np.concatenate(x_gh)
    y_gh=list(y_folds)
    y_hg=y_gh.pop(k)
    y_gh=np.concatenate(y_gh)
    scores.append(svc.fit(x_gh,y_gh).score(x_hg,y_hg))
print(scores)

[0.9388888888888889, 0.9944444444444445, 0.9333333333333333, 0.9666666666666667, 0.9611111111111111, 0.9888888888888889, 0.9666666666666667, 0.9888268156424581, 0.9329608938547486, 0.9664804469273743]


In [1]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
x=iris.data
y=iris.target
np.random.seed(40)
indices=np.random.permutation(len(x))
x_xbn=x[indices[:-30]]
y_xbn=y[indices[:-30]]
x_xbc=x[indices[-30:]]
y_xbc=y[indices[-30:]]
from sklearn.linear_model import Perceptron
sp=Perceptron()
sp.fit(x_xbn,y_xbn)
y_pr_sp=sp.predict(x_xbc)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_xbc,y_pr_sp)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_xbc,y_pr_sp)
print(acc_sc)

[[12  0  0]
 [ 0 10  1]
 [ 0  0  7]]
0.9666666666666667


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [3]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
x=iris.data
y=iris.target
np.random.seed(0)
indices=np.random.permutation(len(x))
x_xbn=x[indices[:-30]]
y_xbn=y[indices[:-30]]
x_xbc=x[indices[-30:]]
y_xbc=y[indices[-30:]]
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(x_xbn,y_xbn)
y_pr_mlp=mlp.predict(x_xbc)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_xbc,y_pr_mlp)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_xbc, y_pr_mlp)
print(acc_sc) 

[[10  0  0]
 [ 0  9  2]
 [ 0  0  9]]
0.9333333333333333


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
