#                                              CLASSIFICATION:

# 1. Wine Dataset

#  K-Nearest Neighbor Algorithm

In [2]:
from sklearn import datasets
import numpy as np

In [3]:
wine=datasets.load_wine()
x=wine.data
y=wine.target

In [4]:
len(x)

178

In [5]:
len(y)

178

In [6]:
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [8]:
x_b=wine.data[:-20]

In [9]:
y_b=wine.target[:-20]

In [10]:
x_oh=wine.data[-20:]

In [11]:
y_oh=wine.target[-20:]

In [12]:
len(y_b)

158

In [13]:
y_b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2])

In [14]:
len(x_oh)

20

In [15]:
len(y_oh)

20

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn=KNeighborsClassifier()

In [18]:
knn.fit(x_b,y_b)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [19]:
y_cxz=knn.predict(x_oh)

In [20]:
y_cxz

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 0, 1])

In [21]:
y_oh

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_oh ,y_cxz)
print(cnf_matrix)

[[ 0  0  0]
 [ 0  0  0]
 [ 4 14  2]]


In [23]:
acc_sc=accuracy_score(y_oh, y_cxz)
print(acc_sc)

0.1


In [24]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_b=list(x_folds)
    x_oh=x_b.pop(k)           
    x_b=np.concatenate(x_b)
    y_b=list(y_folds)
    y_oh=y_b.pop(k)
    y_b=np.concatenate(y_b)
    scores.append(knn.fit(x_b,y_b).score(x_oh,y_oh))
print(scores)

[0.9444444444444444, 0.7777777777777778, 0.8333333333333334, 0.6666666666666666, 0.4444444444444444, 0.7222222222222222, 0.7777777777777778, 0.5555555555555556, 0.35294117647058826, 0.23529411764705882]


# Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier()

In [26]:
x_traine=wine.data[:-20]
y_traine=wine.target[:-20]
x_teste=wine.data[-20:]
y_teste=wine.target[-20:]

In [27]:
decision_tree.fit(x_traine,y_traine)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [28]:
y_prede=decision_tree.predict(x_teste)

In [29]:
y_teste

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
y_prede

array([1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_teste ,y_prede)
print(cnf_matrix)

[[ 0  0  0]
 [ 0  0  0]
 [ 1  1 18]]


In [32]:
acc_sc=accuracy_score(y_teste, y_prede)
print(acc_sc)

0.9


In [33]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_traine=list(x_folds)
    x_teste=x_traine.pop(k)           
    x_traine=np.concatenate(x_traine)
    y_traine=list(y_folds)
    y_teste=y_traine.pop(k)
    y_traine=np.concatenate(y_traine)
    scores.append(decision_tree.fit(x_traine,y_traine).score(x_teste,y_teste))
print(scores)

[0.9444444444444444, 0.8333333333333334, 0.8888888888888888, 0.6666666666666666, 0.7777777777777778, 0.9444444444444444, 0.8888888888888888, 0.7222222222222222, 0.8823529411764706, 0.9411764705882353]


# (c) Naive Baye's Classification

In [34]:
from sklearn.naive_bayes import GaussianNB
naive_bayes=GaussianNB()

In [35]:
x_ter=wine.data[:-20]
y_ter=wine.target[:-20]
x_tef=wine.data[-20:]
y_tef=wine.target[-20:]

In [36]:
naive_bayes.fit(x_ter,y_ter)

GaussianNB(priors=None, var_smoothing=1e-09)

In [37]:
y_pre=naive_bayes.predict(x_tef)

In [38]:
y_pre

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
y_tef

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_tef ,y_pre)
print(cnf_matrix)

[[20]]


In [41]:
acc_sc=accuracy_score(y_tef, y_pre)
print(acc_sc)

1.0


In [42]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_ter=list(x_folds)
    x_tef=x_ter.pop(k)           
    x_ter=np.concatenate(x_ter)
    y_ter=list(y_folds)
    y_tef=y_ter.pop(k)
    y_ter=np.concatenate(y_ter)
    scores.append(naive_bayes.fit(x_ter,y_ter).score(x_tef,y_tef))
print(scores)

[1.0, 0.9444444444444444, 0.8888888888888888, 0.8333333333333334, 0.9444444444444444, 1.0, 1.0, 1.0, 1.0, 1.0]


#  Support Vector Machine

In [43]:
from sklearn import datasets,svm

In [44]:
wine=datasets.load_wine()
x=wine.data
y=wine.target

In [45]:
svc=svm.SVC(C=1,kernel='linear')

In [46]:
x_th=wine.data[:-20]
y_th=wine.target[:-20]
x_ts=wine.data[-20:]
y_ts=wine.target[-20:]

In [47]:
svc.fit(x_th[:-20],y_th[:-20]) 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [48]:
y_predict=svc.predict(x_ts)

In [49]:
svc.predict(x_th)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0])

In [50]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [51]:
cnf_matrix=confusion_matrix(y_ts,y_predict)
print(cnf_matrix)

[[ 0  0]
 [ 3 17]]


In [52]:
acc_sc=accuracy_score(y_ts, y_predict)
print(acc_sc)

0.85


In [1]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_th=list(x_folds)
    x_ts=x_th.pop(k)           
    x_th=np.concatenate(x_th)
    y_th=list(y_folds)
    y_ts=y_th.pop(k)
    y_th=np.concatenate(y_th)
    scores.append(svc.fit(x_th,y_th).score(x_ts,y_ts))
print(scores)

NameError: name 'np' is not defined

In [3]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
x=iris.data
y=iris.target
np.random.seed(40)
indices=np.random.permutation(len(x))
x_xbn=x[indices[:-30]]
y_xbn=y[indices[:-30]]
x_xbc=x[indices[-30:]]
y_xbc=y[indices[-30:]]
from sklearn.linear_model import Perceptron
sp=Perceptron()
sp.fit(x_xbn,y_xbn)
y_pr_sp=sp.predict(x_xbc)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_xbc,y_pr_sp)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_xbc,y_pr_sp)
print(acc_sc)

[[12  0  0]
 [ 0 10  1]
 [ 0  0  7]]
0.9666666666666667


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [4]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
x=iris.data
y=iris.target
np.random.seed(0)
indices=np.random.permutation(len(x))
x_xbn=x[indices[:-30]]
y_xbn=y[indices[:-30]]
x_xbc=x[indices[-30:]]
y_xbc=y[indices[-30:]]
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(x_xbn,y_xbn)
y_pr_mlp=mlp.predict(x_xbc)
from sklearn.metrics import confusion_matrix
cnf_matrix=confusion_matrix(y_xbc,y_pr_mlp)
from sklearn.metrics import accuracy_score
print(cnf_matrix)
acc_sc=accuracy_score(y_xbc, y_pr_mlp)
print(acc_sc) 

[[10  0  0]
 [ 0  9  2]
 [ 0  0  9]]
0.9333333333333333


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# 2.Breast Cancer Dataset

#  K-Nearest Neighbor Algorithm

In [54]:
import numpy as np 

In [55]:
from sklearn import datasets

In [56]:
breast_cancer=datasets.load_breast_cancer()
x=breast_cancer.data
y=breast_cancer.target

In [57]:
len(x)

569

In [58]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [59]:
x_tr=breast_cancer.data[:-100]
y_tr=breast_cancer.target[:-100]
x_te=breast_cancer.data[-100:]
y_te=breast_cancer.data[-100:]

In [60]:
len(x_tr)

469

In [61]:
x_tr

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.314e+01, 2.074e+01, 8.598e+01, ..., 1.181e-01, 2.563e-01,
        8.174e-02],
       [9.668e+00, 1.810e+01, 6.106e+01, ..., 2.500e-02, 3.057e-01,
        7.875e-02],
       [1.760e+01, 2.333e+01, 1.190e+02, ..., 1.996e-01, 2.301e-01,
        1.224e-01]])

In [62]:
y_tr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [63]:
len(y_tr)

469

In [64]:
x_tr.shape

(469, 30)

In [65]:
len(x_tr)

469

In [66]:
len(x_te)

100

In [67]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_tr,y_tr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [68]:
y_prr=knn.predict(x_te)

In [69]:
y_prr

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [70]:
y_te

array([[1.162e+01, 1.818e+01, 7.638e+01, ..., 1.416e-01, 2.660e-01,
        9.270e-02],
       [9.667e+00, 1.849e+01, 6.149e+01, ..., 6.560e-02, 3.174e-01,
        8.524e-02],
       [1.204e+01, 2.814e+01, 7.685e+01, ..., 5.547e-02, 2.404e-01,
        6.639e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [71]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cnf_matrix=confusion_matrix(y_te,y_prr)
print(cnf_matrix)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [72]:
acc_sc=accuracy_score(y_te, y_prr)
print(acc_sc)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [73]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_tr=list(x_folds)
    x_te=x_tr.pop(k)           
    x_tr=np.concatenate(x_tr)
    y_tr=list(y_folds)
    y_te=y_tr.pop(k)
    y_tr=np.concatenate(y_tr)
    scores.append(knn.fit(x_tr,y_tr).score(x_te,y_te))
print(scores)

[0.8070175438596491, 0.9298245614035088, 0.9298245614035088, 0.8947368421052632, 0.9824561403508771, 0.9473684210526315, 0.9473684210526315, 0.9473684210526315, 0.9122807017543859, 0.9642857142857143]


# (b) Decision Tree

In [74]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier()

In [75]:
x_tk=breast_cancer.data[:-100]
y_tk=breast_cancer.target[:-100]
x_tl=breast_cancer.data[-100:]
y_tl=breast_cancer.data[-100:]

In [76]:
decision_tree.fit(x_tk,y_tk)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [77]:
y_py=decision_tree.predict(x_tl)

In [78]:
y_py

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [79]:
y_tl

array([[1.162e+01, 1.818e+01, 7.638e+01, ..., 1.416e-01, 2.660e-01,
        9.270e-02],
       [9.667e+00, 1.849e+01, 6.149e+01, ..., 6.560e-02, 3.174e-01,
        8.524e-02],
       [1.204e+01, 2.814e+01, 7.685e+01, ..., 5.547e-02, 2.404e-01,
        6.639e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [80]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_tl,y_py)
print(cnf_matrix)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [81]:
acc_sc=accuracy_score(y_tl, y_py)
print(acc_sc)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [82]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_tk=list(x_folds)
    x_tl=x_tk.pop(k)           
    x_tk=np.concatenate(x_tk)
    y_tk=list(y_folds)
    y_tl=y_tk.pop(k)
    y_tk=np.concatenate(y_tk)
    scores.append(decision_tree.fit(x_tk,y_tk).score(x_tl,y_tl))
print(scores)

[0.9824561403508771, 0.9122807017543859, 0.8596491228070176, 0.9649122807017544, 0.9122807017543859, 0.9824561403508771, 0.9122807017543859, 0.9649122807017544, 0.9473684210526315, 0.9107142857142857]


# Naive Baye's Classification

In [83]:
from sklearn.naive_bayes import GaussianNB
naive_bayes=GaussianNB()

In [84]:
x_to=breast_cancer.data[:-100]
y_to=breast_cancer.target[:-100]
x_tp=breast_cancer.data[-100:]
y_tp=breast_cancer.data[-100:]

In [85]:
naive_bayes.fit(x_to,y_to)

GaussianNB(priors=None, var_smoothing=1e-09)

In [86]:
y_pb=naive_bayes.predict(x_tp)

In [87]:
y_pb

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [88]:
y_tp

array([[1.162e+01, 1.818e+01, 7.638e+01, ..., 1.416e-01, 2.660e-01,
        9.270e-02],
       [9.667e+00, 1.849e+01, 6.149e+01, ..., 6.560e-02, 3.174e-01,
        8.524e-02],
       [1.204e+01, 2.814e+01, 7.685e+01, ..., 5.547e-02, 2.404e-01,
        6.639e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [89]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_tp,y_pb)
print(cnf_matrix)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [90]:
acc_sc=accuracy_score(y_tp, y_pb)
print(acc_sc)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [91]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_to=list(x_folds)
    x_tp=x_to.pop(k)           
    x_to=np.concatenate(x_to)
    y_to=list(y_folds)
    y_tp=y_to.pop(k)
    y_to=np.concatenate(y_to)
    scores.append(naive_bayes.fit(x_to,y_to).score(x_tp,y_tp))
print(scores)

[0.8947368421052632, 0.8596491228070176, 0.9122807017543859, 0.9298245614035088, 0.9473684210526315, 0.9649122807017544, 0.9824561403508771, 0.9649122807017544, 0.9473684210526315, 0.9642857142857143]


# (d) Support Vector Machine

In [92]:
from sklearn import datasets,svm

In [93]:
breast_cancer=datasets.load_breast_cancer()
x=breast_cancer.data
y=breast_cancer.target

In [94]:
x_tw=breast_cancer.data[:-20]
y_tw=breast_cancer.target[:-20]
x_r=breast_cancer.data[-20:]
y_r=breast_cancer.target[-20:]

In [95]:
svc=svm.SVC(C=1,kernel='linear')
svc.fit(x_tw[:-100],y_tw[:-100]) 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [96]:
y_pg=svc.predict(x_r)

In [97]:
y_pg

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [98]:
y_r

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [99]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cnf_matrix=confusion_matrix(y_r ,y_pg)
print(cnf_matrix)

[[ 6  0]
 [ 0 14]]


In [100]:
acc_sc=accuracy_score(y_r, y_pg)
print(acc_sc)

1.0


In [102]:
x_folds=np.array_split(x,10)
y_folds=np.array_split(y,10)
scores=list()   

for k in range(10):
    x_tw=list(x_folds)
    x_r=x_tw.pop(k)           
    x_tw=np.concatenate(x_tw)
    y_tw=list(y_folds)
    y_r=y_tw.pop(k)
    y_tw=np.concatenate(y_tw)
    scores.append(svc.fit(x_tw,y_tw).score(x_r,y_r))
print(scores)

[0.9122807017543859, 0.9298245614035088, 0.9473684210526315, 0.9649122807017544, 0.9649122807017544, 0.9649122807017544, 0.9824561403508771, 0.9473684210526315, 0.9473684210526315, 0.9642857142857143]
